import { ModelSpec } from '../types/aistudio';

export const GEMINI_MODELS: ModelSpec[] = [
  {
    id: 'gemini-3.7-flash',
    name: 'Gemini 3.7 Flash',
    category: 'Gemini 3 Series',
    description: 'Next-gen hybrid reasoning model with dynamic thinking budget and lightning-fast multimodal intelligence.',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    supportsThinking: true,
    supportsSearch: true,
    supportsCodeExecution: true,
    supportsVision: true,
    supportsAudio: true,
    badge: 'Recommended',
    recommended: true,
  },
  {
    id: 'gemini-3.1-pro-preview',
    name: 'Gemini 3.1 Pro (Preview)',
    category: 'Gemini 3 Series',
    description: 'Advanced reasoning, deep STEM mathematics, architectural code generation, and complex analysis.',
    contextWindow: 2097152,
    maxOutputTokens: 8192,
    supportsThinking: true,
    supportsSearch: true,
    supportsCodeExecution: true,
    supportsVision: true,
    supportsAudio: true,
    badge: 'Complex Reasoning',
  },
  {
    id: 'gemini-3.1-flash-lite',
    name: 'Gemini 3.1 Flash Lite',
    category: 'Gemini 3 Series',
    description: 'Ultra-low latency, cost-effective high-throughput model for high-scale agent workflows.',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    supportsThinking: false,
    supportsSearch: true,
    supportsCodeExecution: true,
    supportsVision: true,
    supportsAudio: false,
    badge: 'Fast & Lightweight',
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    category: 'Gemini 2.5 Series',
    description: 'High-speed multimodal workhorse for chat, classification, summarization, and search grounding.',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    supportsThinking: true,
    supportsSearch: true,
    supportsCodeExecution: true,
    supportsVision: true,
    supportsAudio: true,
    badge: '1M Context',
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    category: 'Gemini 2.5 Series',
    description: 'Flagship frontier model for complex multimodality, massive 2M token context, and deep reasoning.',
    contextWindow: 2097152,
    maxOutputTokens: 8192,
    supportsThinking: true,
    supportsSearch: true,
    supportsCodeExecution: true,
    supportsVision: true,
    supportsAudio: true,
    badge: '2M Context',
  },
  {
    id: 'gemini-3.1-flash-image',
    name: 'Gemini 3.1 Flash Image',
    category: 'Specialized Modalities',
    description: 'High-resolution image generation (up to 4K) and image editing with Google Image Search grounding.',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    supportsVision: true,
    supportsSearch: true,
    badge: 'Image Studio',
  },
  {
    id: 'veo-3.1-generate-preview',
    name: 'Veo 3.1 Video Generator',
    category: 'Specialized Modalities',
    description: 'High-definition video generation from text prompts and starting frames.',
    contextWindow: 64000,
    maxOutputTokens: 2048,
    supportsVision: true,
    badge: 'Video Gen',
  },
];
