import { ColorPalette, DevicePreset, TextureType, GuideType } from '../types';

export const PALETTES: ColorPalette[] = [
  // --- White / Light Mode Series (Primary) ---
  {
    id: 'pure-white',
    name: 'Pristine White',
    subtitle: 'Ultra-clean studio white canvas with sand gold accents',
    mode: 'light',
    bgBase: '#FFFFFF',
    bgSurface: '#F7F7F6',
    bgElevated: '#FFFFFF',
    borderColor: '#E7E6E2',
    glowColor: 'rgba(212, 163, 115, 0.18)',
    accentWarmth: '#C48A4F',
    textPrimary: '#141413',
    textSecondary: '#6B6862',
    textTertiary: '#9E9B93',
    tagColor: '#F3EFE9',
  },
  {
    id: 'warm-alabaster',
    name: 'Warm Alabaster',
    subtitle: 'Refined soft porcelain with warm amber undertones',
    mode: 'light',
    bgBase: '#FAF8F5',
    bgSurface: '#F2EDE5',
    bgElevated: '#FFFFFF',
    borderColor: '#E5DED4',
    glowColor: 'rgba(225, 145, 80, 0.20)',
    accentWarmth: '#BA7837',
    textPrimary: '#1C1917',
    textSecondary: '#78716C',
    textTertiary: '#A8A29E',
    tagColor: '#EFE9E0',
  },
  {
    id: 'soft-sand',
    name: 'Soft Sandstone',
    subtitle: 'Organic linen and warm architectural sandstone',
    mode: 'light',
    bgBase: '#F6F3EE',
    bgSurface: '#EAE4DA',
    bgElevated: '#FFFFFF',
    borderColor: '#DDD4C7',
    glowColor: 'rgba(212, 163, 115, 0.22)',
    accentWarmth: '#AD6E30',
    textPrimary: '#201D1A',
    textSecondary: '#6D655C',
    textTertiary: '#998F84',
    tagColor: '#E8E1D5',
  },
  {
    id: 'minimal-silver',
    name: 'Minimal Silver',
    subtitle: 'Crisp contemporary neutral with platinum clarity',
    mode: 'light',
    bgBase: '#F9FAFB',
    bgSurface: '#F1F3F5',
    bgElevated: '#FFFFFF',
    borderColor: '#E2E5E8',
    glowColor: 'rgba(180, 190, 205, 0.20)',
    accentWarmth: '#6B7280',
    textPrimary: '#111827',
    textSecondary: '#4B5563',
    textTertiary: '#9CA3AF',
    tagColor: '#EBF0F5',
  },

  // --- Dark Mode Series ---
  {
    id: 'warm-basalt',
    name: 'Warm Basalt',
    subtitle: 'Immersive graphite series with sand amber warmth',
    mode: 'dark',
    bgBase: '#1A1A1A',
    bgSurface: '#222222',
    bgElevated: '#242424',
    borderColor: '#2D2D2D',
    glowColor: 'rgba(212, 163, 115, 0.22)',
    accentWarmth: '#D4A373',
    textPrimary: '#E6E1D6',
    textSecondary: '#8C887E',
    textTertiary: '#4A4740',
    tagColor: '#242424',
  },
  {
    id: 'deep-umber',
    name: 'Deep Umber',
    subtitle: 'Rich smoked caramel & bronze undertones',
    mode: 'dark',
    bgBase: '#151311',
    bgSurface: '#1f1a17',
    bgElevated: '#28221d',
    borderColor: '#382f27',
    glowColor: 'rgba(225, 145, 80, 0.22)',
    accentWarmth: '#E59A60',
    textPrimary: '#F6ECE5',
    textSecondary: '#A8978A',
    textTertiary: '#584D3D',
    tagColor: '#261F1A',
  },
  {
    id: 'smoked-obsidian',
    name: 'Smoked Obsidian',
    subtitle: 'Ultra-dark graphite with copper sheen',
    mode: 'dark',
    bgBase: '#121213',
    bgSurface: '#1A1A1C',
    bgElevated: '#222226',
    borderColor: '#2E2E33',
    glowColor: 'rgba(212, 163, 115, 0.16)',
    accentWarmth: '#CCA38B',
    textPrimary: '#EDE8EA',
    textSecondary: '#948D93',
    textTertiary: '#4A4740',
    tagColor: '#202024',
  },
  {
    id: 'matte-anthracite',
    name: 'Matte Anthracite',
    subtitle: 'Studio industrial graphite neutral',
    mode: 'dark',
    bgBase: '#161617',
    bgSurface: '#1E1E20',
    bgElevated: '#262629',
    borderColor: '#303035',
    glowColor: 'rgba(220, 195, 165, 0.16)',
    accentWarmth: '#D6D1C4',
    textPrimary: '#F0EFF2',
    textSecondary: '#8C887E',
    textTertiary: '#4A4740',
    tagColor: '#222225',
  },
  {
    id: 'bronze-graphite',
    name: 'Bronze Series',
    subtitle: 'Earthy raw umber with amber highlight nodes',
    mode: 'dark',
    bgBase: '#171614',
    bgSurface: '#211E1A',
    bgElevated: '#2B2620',
    borderColor: '#3A332B',
    glowColor: 'rgba(212, 163, 115, 0.25)',
    accentWarmth: '#D4A373',
    textPrimary: '#FAF4EC',
    textSecondary: '#A69B8D',
    textTertiary: '#584D3D',
    tagColor: '#2C251E',
  },
  {
    id: 'raw-graphite',
    name: 'Raw Mineral',
    subtitle: 'Tactile natural graphite mineral slate',
    mode: 'dark',
    bgBase: '#141415',
    bgSurface: '#1D1D1F',
    bgElevated: '#252528',
    borderColor: '#2F2F34',
    glowColor: 'rgba(230, 210, 185, 0.18)',
    accentWarmth: '#E6E1D6',
    textPrimary: '#F2F2F4',
    textSecondary: '#8C887E',
    textTertiary: '#4A4740',
    tagColor: '#232326',
  },
  {
    id: 'studio-graphite',
    name: 'AI Studio Slate',
    subtitle: 'Google AI Studio official dark & light workspace tone',
    mode: 'dark',
    bgBase: '#131314',
    bgSurface: '#1E1F20',
    bgElevated: '#282A2C',
    borderColor: '#37393B',
    glowColor: 'rgba(138, 180, 248, 0.25)',
    accentWarmth: '#8AB4F8',
    textPrimary: '#E3E3E3',
    textSecondary: '#C4C7C5',
    textTertiary: '#8E918F',
    tagColor: '#282A2C',
  },
];

export interface DeviceSpec {
  id: DevicePreset;
  name: string;
  category: string;
  width: number;
  height: number;
  radius: number;
  bezel: number;
  notchType: 'island' | 'pill' | 'punch' | 'none';
  aspectRatio: string;
}

export const DEVICE_SPECS: Record<DevicePreset, DeviceSpec> = {
  fullscreen: {
    id: 'fullscreen',
    name: 'Full Screen Preview',
    category: 'Fluid Workspace',
    width: 0,
    height: 0,
    radius: 24,
    bezel: 0,
    notchType: 'none',
    aspectRatio: 'auto',
  },
  desktop: {
    id: 'desktop',
    name: 'Desktop Studio',
    category: '16:10 Desktop',
    width: 1024,
    height: 680,
    radius: 20,
    bezel: 0,
    notchType: 'none',
    aspectRatio: '16 / 10',
  },
  iphone16pro: {
    id: 'iphone16pro',
    name: 'Pro Max Frame',
    category: '19.5:9 Flagship',
    width: 390,
    height: 844,
    radius: 54,
    bezel: 10,
    notchType: 'island',
    aspectRatio: '390 / 844',
  },
  pixel9: {
    id: 'pixel9',
    name: 'Modern Slate',
    category: '20:9 Flagship',
    width: 384,
    height: 832,
    radius: 46,
    bezel: 9,
    notchType: 'punch',
    aspectRatio: '384 / 832',
  },
  compact: {
    id: 'compact',
    name: 'Compact Minimal',
    category: '18:9 Minimalist',
    width: 360,
    height: 740,
    radius: 40,
    bezel: 8,
    notchType: 'punch',
    aspectRatio: '360 / 740',
  },
  slate: {
    id: 'slate',
    name: 'Tablet Canvas',
    category: '4:3 Slate',
    width: 580,
    height: 780,
    radius: 36,
    bezel: 14,
    notchType: 'none',
    aspectRatio: '580 / 780',
  },
  frameless: {
    id: 'frameless',
    name: 'Frameless Glass',
    category: 'Pure Viewport',
    width: 390,
    height: 844,
    radius: 32,
    bezel: 0,
    notchType: 'none',
    aspectRatio: '390 / 844',
  },
};

export const TEXTURE_OPTIONS: { id: TextureType; name: string; description: string }[] = [
  { id: 'velvet', name: 'Velvet Matte', description: 'Ultra-fine soft graphite micro-texture' },
  { id: 'grain', name: 'Tactile Grain', description: 'Organic paper & sandstone tactile grain' },
  { id: 'dotmatrix', name: 'Dot Matrix', description: 'Subtle 12px engineering blueprint dots' },
  { id: 'isometric', name: 'Isometric Grid', description: 'Precision drafting & architectural lines' },
  { id: 'brushed', name: 'Brushed Alloy', description: 'Fine directional micro-machined grain' },
  { id: 'clean', name: 'Pure Minimal', description: 'Crisp, untextured pristine OLED canvas' },
];

export const GUIDE_OPTIONS: { id: GuideType; name: string; description: string; icon: string }[] = [
  { id: 'immersive-series', name: 'Immersive UI', description: 'Curated warm graphite layout card architecture', icon: 'Sparkles' },
  { id: 'minimal-clock', name: 'Zen Clock', description: 'Refined ambient typography time widget', icon: 'Clock' },
  { id: 'safe-area', name: 'Safe Areas', description: 'Status bar, dynamic island & home indicators', icon: 'Shield' },
  { id: 'grid-8pt', name: '8pt System Grid', description: 'Modular 8pt design layout grid columns', icon: 'Grid' },
  { id: 'rule-of-thirds', name: 'Composition', description: 'Rule of thirds & golden ratio intersections', icon: 'Crosshair' },
  { id: 'wireframe-clean', name: 'Clean Wireframe', description: 'Light placeholder cards & navigation bar', icon: 'Layout' },
  { id: 'wireframe-content', name: 'Feed Wireframe', description: 'Article/Media layout placeholders', icon: 'Columns' },
  { id: 'none', name: 'Pure Blank', description: 'Zero distractions, serene blank canvas', icon: 'Maximize2' },
];
